### ISSUE TITLE
Remove SibraService

### ISSUE THREAD

**Issue by hausheer** [netsec-ethz/scion-utilities#5]
`TYPES_TO_KEYS` must not include `sibra_server`, the new scion version does not include it anymore.

@jonghoonkwon could you maybe take a look at this?

**Comment by jonghoonkwon** [comment]
@hausheer Yes, you're right. I'm planing some update for the `local_config_util.py` and I'll fix it with the update. Thanks for the heads up.

**Comment by jonghoonkwon** [comment]
Solved! (#7)
